# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('4802', 'Paper'), ('4820', 'Register'), ('4820', 'Books'), ('4820', 'Folders'), ('3215', 'Ball pen'), ('4419', 'Table'), ('9609', 'Pencil'), ('4202', 'Wallets')], default='Paper', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('hsn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Taxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('igst', models.FloatField()),
            ],
        ),
    ]
