# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='tax1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='result',
            name='tax2',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='result',
            name='tax3',
            field=models.FloatField(default=None),
        ),
    ]
